### ISSUE TITLE
A few small details

### ISSUE THREAD

**Issue by Hangover3832** [andres-manzano/nvidia-cuda-wsl-setup-guide#1]
This article finally made me CUDA working on WSL2. Thank you very much. I have noticed two things:

- I run into the problem that I had Ubuntu already installed with WSL1, so `wsl --set-default-version 2` did not do anything for me. It took me quite a while to find out that the distribution must be updated with `wsl --set-version <distro-name> 2`. Perhaps you want to mention this in your article.
- `sudo apt update && upgrade` should be `sudo apt update && sudo apt upgrade`

So long.

**Comment by andres-manzano** [comment]
My pleasure! It's great to know that this guide helped you to use Cuda.

Regarding the WSL installation process. From the beginning, the guide mentioned to install WSL2, but I'll make sure to clarify it must be updated to version 2 as you pointed out.

Regarding the command, it should be work with ```sudo apt update && upgrade``` as well as ```sudo apt update && sudo apt upgrade```. I'll include both commands in the guide too.

Thanks for your feedback.
